# We are using Playwright but you may use your E2E framework of choice
name: Playwright Tests

on:
  deployment_status:

jobs:
  e2e:
    if: github.event_name == 'deployment_status' && github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: npm ci && npx playwright install --with-deps
    - name: Run tests
      run: echo "npx playwright test"
    - name: Run tests 02
      run: echo ${{ github.event_name }}
    - name: Run tests 03
      run: echo ${{ github.event.deployment_status.state }}
    - name: Run tests 04
      run: echo ${{ github.event.deployment_status.environment }}
    - name: Run tests 05
      run: echo ${{ github.event.pull_request.merged }}
